site_name: GetSecurity
site_url: https://ajhstn.github.io
site_description: Information Security for everyone.
site_author: Andrew Huddleston
repo_url: https://github.com/ajhstn/getsecurity
#remote_branch: master

pages:
  - Home: 
    - Home: index.md
    - Toc: toc.md
  - Start Here: start-here.md
