site_name: GetSecurity
site_url: https://ajhstn.github.io
site_description: Information Security for everyone.
site_author: Andrew Huddleston
repo_url: https://github.com/ajhstn/getsecurity

pages:
  - Home: 
    - Home: index.md
    - Toc: toc.md
    - Change Log: change-log.md
  - Start Here: 
    - Security Essentials: start-here.md
    - Access Control: record-of-access.md
